name: Deploy to FTP
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          echo "Node modules installed:"
          ls -la node_modules
      
      - name: Build
        run: |
          npm run build
          echo "Build output:"
          ls -la dist/
      
      - name: Verify build artifacts
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: dist directory not found"
            exit 1
          fi
          echo "Build directory contents:"
          ls -la dist/
          echo "Total files in build:"
          find dist -type f | wc -l
      
      - name: Test FTP connection
        run: |
          echo "Testing FTP connection..."
          echo "FTP Host: ${{ secrets.FTP_HOST }}"
          echo "Target Directory: ${{ secrets.FTP_TARGET_DIR }}"
          nc -zv ${{ secrets.FTP_HOST }} 21 || echo "FTP port test failed"
      
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ${{ secrets.FTP_TARGET_DIR }}
          dangerous-clean-slate: true
          timeout: 120000
          log-level: verbose
          dry-run: false
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**